name: CI
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
    branches:
      - main
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Check formatting
      run: test -z $(gofmt -l **.go)
    - name: Run tests
      run: |
        go test -race -v -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      if: success()
